package com.scms.backend.membership;
import java.math.BigDecimal; import java.math.BigInteger; import java.net.URLEncoder; import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.sql.Timestamp; import java.time.Clock; import java.time.Instant; import java.time.temporal.ChronoUnit; import java.util.Map; import java.util.UUID;
import com.scms.backend.account.*; import com.scms.backend.auth.InvalidAuthenticatedAccountException;
import org.springframework.beans.factory.annotation.Value; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service class SepayService { private final JdbcTemplate db; private final AccountRepository accounts; private final Clock clock; private final String bankCode,bankAccount,bankAccountName,webhookApiKey;
 SepayService(JdbcTemplate db,AccountRepository accounts,Clock clock,@Value("${sepay.bank-code:}")String bankCode,@Value("${sepay.bank-account:}")String bankAccount,@Value("${sepay.bank-account-name:}")String bankAccountName,@Value("${sepay.webhook-api-key:}")String webhookApiKey){this.db=db;this.accounts=accounts;this.clock=clock;this.bankCode=bankCode;this.bankAccount=bankAccount;this.bankAccountName=bankAccountName;this.webhookApiKey=webhookApiKey;}
 @Transactional SepayPaymentResponse create(UUID actor,UUID orderId){if(!accounts.existsByIdAndRoleAndStatus(actor,AccountRole.MEMBER,AccountStatus.ACTIVE))throw new InvalidAuthenticatedAccountException();var o=db.queryForMap("select * from membership_orders where id=? and member_account_id=? for update",orderId,actor);if(!"PENDING_PAYMENT".equals(o.get("status")))throw new SepayValidationException("Order is not payable");if(bankCode.isBlank()||bankAccount.isBlank())throw new SepayValidationException("SePay bank configuration is missing");Instant exp=clock.instant().plus(24,ChronoUnit.HOURS);db.update("update membership_orders set expires_at=?,updated_at=current_timestamp where id=?",Timestamp.from(exp),orderId);String ref="SCMS-"+o.get("order_number");UUID payment=UUID.randomUUID();db.update("insert into payments(id,order_id,method,status,amount,currency_code,provider,provider_reference) values(?,?, 'BANK_TRANSFER','PENDING',?,'VND','SEPAY',?)",payment,orderId,o.get("price_amount_snapshot"),ref);String qr="https://qr.sepay.vn/img?bank="+enc(bankCode)+"&acc="+enc(bankAccount)+"&template=compact&amount="+o.get("price_amount_snapshot")+"&des="+enc(ref)+(bankAccountName.isBlank()?"":"&accountName="+enc(bankAccountName));return new SepayPaymentResponse(payment,orderId,String.valueOf(o.get("order_number")),new BigDecimal(o.get("price_amount_snapshot").toString()).toBigIntegerExact(),"VND","SEPAY",ref,qr,exp,"PENDING");}
 @Transactional Map<String,Object> webhook(String supplied,SepayWebhookRequest r){if(webhookApiKey.isBlank()||supplied==null||!MessageDigest.isEqual(supplied.getBytes(StandardCharsets.UTF_8),webhookApiKey.getBytes(StandardCharsets.UTF_8)))throw new SepayValidationException("Invalid SePay webhook credentials");var p=db.queryForMap("select p.*,o.* from payments p join membership_orders o on o.id=p.order_id where p.provider='SEPAY' and p.provider_reference=? for update",r.code());if("PAID".equals(p.get("status")))return p;if(!"in".equalsIgnoreCase(r.transferType())||!new BigInteger(p.get("price_amount_snapshot").toString()).equals(r.transferAmount()))throw new SepayValidationException("SePay payment does not match order");UUID payment=(UUID)p.get("id");UUID order=(UUID)p.get("order_id");db.update("update payments set status='PAID',provider_transaction_id=?,paid_at=current_timestamp,updated_at=current_timestamp where id=? and status='PENDING'",String.valueOf(r.id()),payment);Instant now=clock.instant();db.update("update membership_orders set status='PAID',paid_at=?,expires_at=null,updated_at=current_timestamp where id=?",Timestamp.from(now),order);UUID membership=UUID.randomUUID();db.update("insert into memberships(id,member_account_id,order_id,offer_id,plan_code_snapshot,offer_name_snapshot,price_amount_snapshot,currency_code_snapshot,duration_days_snapshot,status,starts_at,ends_at) values(?,?,?,?,?,?,?,?,?,'ACTIVE',?,?)",membership,p.get("member_account_id"),order,p.get("offer_id"),p.get("plan_code_snapshot"),p.get("offer_name_snapshot"),p.get("price_amount_snapshot"),p.get("currency_code_snapshot"),p.get("duration_days_snapshot"),Timestamp.from(now),Timestamp.from(now.plusSeconds(((Number)p.get("duration_days_snapshot")).longValue()*86400)));UUID receipt=UUID.randomUUID();db.update("insert into receipts(id,receipt_number,payment_id,order_id,member_account_id,amount_snapshot,currency_code_snapshot,payment_method_snapshot) values(?,?,?,?,?,?,?,?)",receipt,"RC-"+receipt,payment,order,p.get("member_account_id"),p.get("price_amount_snapshot"),p.get("currency_code_snapshot"),"BANK_TRANSFER");return Map.of("paymentId",payment,"membershipId",membership,"receiptId",receipt,"status","PAID");}
 private String enc(String s){return URLEncoder.encode(s,StandardCharsets.UTF_8);}}

