spring.application.name=scms-backend
server.port=${PORT:8080}
server.servlet.context-path=/api/v1

spring.flyway.clean-disabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jackson.time-zone=UTC
spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'UTC'
spring.mvc.problemdetails.enabled=true
springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

scms.session-lifecycle-delay-ms=30000

scms.security.access-token-ttl=15m
scms.security.refresh-token-ttl=7d
sepay.bank-code=${SEPAY_BANK_CODE:}
sepay.bank-account=${SEPAY_BANK_ACCOUNT:}
sepay.bank-account-name=${SEPAY_BANK_ACCOUNT_NAME:}
sepay.webhook-api-key=${SEPAY_WEBHOOK_API_KEY:}
